# Apa itu cron job ?
# - Cron job adalah aplikasi untuk penjadwalan yang biasanya ada di sistem operasi unix
# - Dengan menggunakan cron job kita bisa menjadwalkan aplikasi berjalan sesuai jadwal yang kita inginkan
# - Kubernetes mendukung resource cron job, dimana cara kerjanya mirip job, hanya saja kalo job berjalan sekali, tapi cron job bisa berjalan berulang kali sesuai dengan jadwal yang kita inginkan
# - Cron job juga bisa memungkinkan kita untuk menjalankan aplikasi dengan waktu yang telah ditentukan

# Contoh penggunaan cron job
# - Aplikasi untuk membuat laporan harian
# - Aplikasi untuk membackup data secara berkala
# - Aplikasi untuk mengirim data tagihan tiap bulang ke pihak lain
# - Aplikasi untuk menarik dana pinjaman yang jatuh tempo bulanan
# - Dan sejenisnya

# Untuk mencoba cron job
# - https://crontab.guru/#*_*_*_*

# Membuat cron job
# - kubectl create -f filename.yaml

# Melihat cron job
# - kubectl get cronjobs
# - kubectl get cronjob

# Menghapus cron job
# - kubectl delete cronjob cronjobname

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-name
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotation-value
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      selector:
        matchLabels:
          label-key1: label-value1
      template:
        metadata:
          name: nama-pod
          labels:
            label-key1: label-value1
        spec:
          restartPolicy: Never
          containers:
            - name: container-name
              image: image-name
              ports:
                - containerPort: 80