# Sensitive data
# - Saat kita menggunakan ConfigMap, maka data yang ada dalam ConfigMap dianggap tidak sensitive
# - Tapi, kadang konfigurasi aplikasi kita, butuh data yang sifatnya sensitive, seperti username, password database, API Key, Secret Key, dan sejenisnya
# - Untuk menyimpan jenis data sensitive seperti ini, di kubernetes kita bisa menggunakan object yang disebut Secret. Secret sama seperti ConfigMap, berisikan data key-value

# Secret
# - Kubernetes menyimpan secret secara aman dengan cara hanya mendistribusikan Secret pada Node yang memang hanya membutuhkan Secret tersebut
# - Secret selalu disimpan di memory di node dan tidak pernah disimpan di physical storage
# - Di master node sendiri (lebih tepatnya di etcd), secret disimpan dengan cara di encrypt, sehingga menjadi lebih aman
# - Secara sederhana, gunakan ConfigMap untuk konfigurasi yang tidak sensitif, dan gunakan secret untuk konfigurasi yang bersifat sensitif

# Membuat secret
# - kubectl create -f filename.yaml

# Melihat secret
# - kubectl get secrets
# - kubectl describe secret secretname

# Menghapus secret
# - kubectl delete secret secretname

apiVersion: v1
kind: Secret
metadata:
  name: configmap-name
data:
  ENV: base64(VALUE)
stringData:
  ENV: VALUE